### ISSUE TITLE
AWS IAM security improvements 

### ISSUE THREAD

**Issue by justinPemberton** [hackforla/devops-security#24]
### Depdendency
- Move this issue to new issue approval Colum once its child issues are closed, to see next steps

### Overview
Improve IAM to make instituting procedures or policies easier 
### Action Items
Child Issues: 
- [ ] https://github.com/hackforla/devops-security/issues/60
- [x] https://github.com/hackforla/devops-security/issues/80
- [x] https://github.com/hackforla/devops-security/issues/22
- [x] https://github.com/hackforla/devops-security/issues/81
- [x] https://github.com/hackforla/devops-security/issues/82
- [ ] account lockdown issue
- [ ] use it or lose it policy
- [ ] least privilege permission records

Decision Records
- [x] https://github.com/hackforla/devops-security/issues/22 
- [ ] #60
- [x] #59
- [x] #62
- [x] #63
- [x] #64
- [x] #65
- [x] #61
### Resources/Instructions
- https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html
- [OPS: IAM AWS](https://docs.google.com/spreadsheets/d/1m9n-KdT2NqIShYFnPlgmIv8Wjh0L5sGFsm4se3hYBEw)
- https://github.com/hackforla/website/wiki/Decision-Records - Hack for LA team decision record examples

**Comment by ExperimentsInHonesty** [comment]
# Template for child issues
```
### Overview
We need to figure out Industry Guidance and document what should be in the [name of thing] policy, so that we can create actionable HfLA best practices.

### Action Items
- [ ] Identify and document in a comment who is the authoritative source for guidance (might be multiple places), e.g., AWS, etc.
- [ ] Write up the recommendation in the form of a Decision Record as a draft comment.  Use template on (resource 1.01) and reference the source
- [ ] Add to DevOps team agenda (resource 1.02) for review and approval
- [ ] Add to wiki and link to (resource 1.01 and 1.03)

### Resources/Instructions
#### Used during issue
- 1.01 Decision Records Implemented
- 1.02 https://github.com/hackforla/ops/issues/100
- 1.03 Decision Records 

#### created by issue
2.01 Decision Record for [name of thing]
```

**Comment by ExperimentsInHonesty** [comment]
@sudhara all the issues linked to this epic need to have the template as the body of the issue.  
- [ ] Fix the body of each issues
- [ ] add the draft label
- [ ] add the ready for product label
- [ ] make sure its in the new issue approval column.

**Comment by ExperimentsInHonesty** [comment]
@sudhara Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by sudhara** [comment]
Created issues for team to work on instead of Decision Records. 3 more issues to be created. Will finish it next week.
