### ISSUE TITLE
Pre-work Checklist: DevOps-Security-Member: Alex English

### ISSUE THREAD

**Issue by ale210** [hackforla/devops-security#39]
### Prerequisite
We are looking forward to having you on our team. Please ensure you have prior experience with the HfLA website team before contributing to our repository.
### Overview
As a new member on the HfLA devops-security team, fill in the following fields as you complete each onboarding item.

### Special Notes
1. Keep this issue open until you've completed all steps, including learning to provide updates for longer tasks.
2. Normally, handle one issue at a time, but this one is an exception as it teaches how to manage multiple tasks.
3. Work on action items sequentially, but proceed if possible. For example, set up your dev environment without waiting for the weekly meeting.

### Action Items

- [x] Before starting to work on the below instructions, make sure to join the #ops Slack Channel. And are a member of `devops-security` repository.
- [x] Self-assign this issue (gear in right side panel).
- [x] Add this issue to the Project Board under the Projects section (gear in right side panel).
- [x] Attend weekly team meeting, Wednesdays 6-8pm PST.
  - [x] Note: There are no meetings on the 1st-7th of every month.
- [x] Complete the steps in [Creating a personal AWS account](https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md#creating-a-personal-aws-account) and [Login as root user & setup MFA](https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md#login-as-root-user-&-setup-mfa).
- [x] Read and follow the instructions in [Setting up IAM and AWS CLI](https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md#setting-up-iam-and-aws-cli) for:
    - [x] [Creating an IAM User](https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md#create-an-iam-group)
    - [x] [Creating an IAM Group](https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md#create-an-iam-group)
    - [x] [Attaching IAM user to IAM Group](https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md#attach-iam-user-to-iam-group)
    - [x] [Providing `AdministratorAccess` policy to IAM group](https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md#attach-administratoraccess-policy-to-iam-group)
    - [x] Log in as the newly created user instead of continuing to log in as the root user (it is not recommended to login with root access).
    - [x] [Generating user access keys](https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md#generating-access-keys-for-aws-cli)
- [x] Complete the instructions in [AWS Documentation](https://docs.aws.amazon.com/cli/v1/userguide/cli-chap-install.html) and choose your operating system to install AWS CLI. 
- [x] Complete the instruction in [AWS Documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-authentication-short-term.html) to setup the AWS CLI.
- [x] Read follow the instructions in [Creating a backend state](https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md#creating-backend-state).
- [x] Install Terraform locally by following the instructions of the installation guide mentioned in [Installing Terraform](https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md#installing-terraform)
- [x] Install Terraform Docs locally by following the instructions of the installation guide mentioned in [Installing Terraform docs](https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md#installing-terraform-docs)
- [x] Complete the instructions in [Clone the repository](https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md#clone-the-repository)
- [x] Submit a [new request](https://github.com/hackforla/devops-security/issues/new?assignees=&labels=enhancement&projects=&template=request-aws-iam-resources.yml) to create new AWS user account and then self-assign this issue.
- [x] Create a new branch from main by executing the command

    ```bash
    git checkout -b issue-number-add-new-iam-user

    ```
- [x] Navigate to the `aws-user.tf` file and add your user information and follow the below template.

    ```bash
    
    module "iam_user_testiamuser" {
    source = "./modules/aws-users"

    user_name = "testiamuser"
    user_tags = {
      "Project"      = "devops-security"
      "Access Level" = "1"
    }
    user_groups = ["read-only-group"]
    }

    ```
- [x] In your code editor navigate to `terraform` directory. `cd terraform`
- [x] Execute the command `terraform init` to initialize terraform in the directory. Address any failures that arise (if any).
- [x] Execute the command `terraform plan` this will output a plan replicating the same IAM resources as the devops security account. Address any failures that arise (if any).
- [x] Then execute the command `terraform apply` this will create all of the resources that are currently managed by Devops Security. All of the resources created here incur zero cost except for the Dynamo DB installation, which should remain in the free tier.
      - [ ] ** If you have cost concerns, Run a Terraform Destroy to take down all of the resources you created (don't worry, you can recreate them just as quickly). **
- [x] Once you have tested your changes, stage them in git with 
    - [x] `git status` command.
    - [x] then `git add path/to/file` (you can copy from above output for the file path).
- [x] Commit the changes by executing `git commit -m "briefly describing the changes"`.
- [x] Push the changes with `git push --set-upstream origin name-of-branch`

**Comment by ale210** [comment]
@chelseybeck I believe this is all done? not sure if I should set a status or anything

**Comment by chelseybeck** [comment]
@ale210 - did you run into any issues working on this?

**Comment by ale210** [comment]
I had some issues with branch permissions but we resolved this prior to going away for the break

**Comment by drakeredwind01** [comment]
Hi, 
how have you been doing?
i'm having trouble starting from the part of:
- [x] Execute the command `terraform init` to initialize terraform in the directory. Address any failures that arise (if any).
would you mind guiding me through this challenging part? i'm using windows and pycharm
it's fastest to contact me here https://discord.gg/WbcWqVq 
please use '@drakeredwind01' to notify me

**Comment by ale210** [comment]
all set
